### ISSUE TITLE
Quart 0.18.0 not supported with Markupsafe 2.1.1

### ISSUE THREAD

**Issue by zigazajc007** [pallets/quart#171]
```
Traceback (most recent call last):
  File "/usr/local/bin/rabbitmonitor", line 5, in <module>
    from rabbitmonitor import start
  File "/usr/local/lib/python3.9/dist-packages/rabbitmonitor/__init__.py", line 1, in <module>
    from quart import Quart
  File "/usr/local/lib/python3.9/dist-packages/quart/__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "/usr/local/lib/python3.9/dist-packages/quart/app.py", line 49, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "/usr/local/lib/python3.9/dist-packages/quart/asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "/usr/local/lib/python3.9/dist-packages/quart/debug.py", line 6, in <module>
    from jinja2 import Template
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/lib/python3/dist-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/lib/python3/dist-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.9/dist-packages/markupsafe/__init__.py)
```

markupsafe removed soft_unicode and make a breaking changed in version 2.1.1.

To duplicate this issue just execute:
pip install quart
and then run any program that depend on quart.

Quart should be supported with markupsafe 2.1.1.

Environment:

- Python version: 3.9
- Quart version: 0.18.0

**Comment by pgjones** [comment]
I think you need to update your Jinja2 version - the error reported is from Jinja2 rather than from Quart.

**Comment by zigazajc007** [comment]
Thanks updating Jinja2 solved the problem.
