### ISSUE TITLE
Test client fails when running 1.18.1/1.18.2 but is fine for 1.18.0

### ISSUE THREAD

**Issue by enchant97** [pallets/quart#192]
When running a unittest test with the `test_client` it fails with an exception. It runs fine under Quart 1.18.0.

Code Snippet

```python
class TestIndex(IsolatedAsyncioTestCase):
    async def test_valid(self):
        client = create_app().test_client()  # <------ Exception is raised here
        response = await client.get("/")
        data = await response.get_data(as_text=True)

        self.assertIn("Hasty Paste", data)
```

Full Code Available [here](https://github.com/enchant97/hasty-paste/blob/f7eb053dbf0049d43fc63ef6e81f816337ec73f2/tests/test_views.py).

Exception:

```
Traceback (most recent call last):
  File "/usr/lib/python3.10/unittest/async_case.py", line 64, in _callTestMethod
    self._callMaybeAsync(method)
  File "/usr/lib/python3.10/unittest/async_case.py", line 87, in _callMaybeAsync
    return self._asyncioTestLoop.run_until_complete(fut)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/lib/python3.10/unittest/async_case.py", line 101, in _asyncioLoopRunner
    ret = await awaitable
  File "/home/leo/Workspaces/hasty-paste/tests/test_views.py", line 42, in test_valid
    response = await client.get("/")
  File "/home/leo/Workspaces/hasty-paste/.venv/lib/python3.10/site-packages/quart/testing/client.py", line 234, in get
    return await self.open(*args, method="GET", **kwargs)
  File "/home/leo/Workspaces/hasty-paste/.venv/lib/python3.10/site-packages/quart/testing/client.py", line 99, in open
    response = await self._make_request(
TypeError: create_test_client_mixin.<locals>.TestClientMixin._make_request() takes from 13 to 14 positional arguments but 15 were given
```

Environment:

- Python version: 3.10.7
- Quart version: 1.18.1 & 1.18.2
- Linux

**Comment by pgjones** [comment]
What Quart extensions are you using? If it is Quart-Schema then that needs an upgrade.

**Comment by enchant97** [comment]
ah yes Quart-Schema is on 0.13
