### ISSUE TITLE
Conflict with Werkzeug

### ISSUE THREAD

**Issue by Nicolas-M15** [pallets/quart#209]
I need to use some Werzeug functions in Quart:

    from werkzeug.security import generate_password_hash, check_password_hash

Unfortunately, I have an error:

```
hypercorn main:app
Traceback (most recent call last):
  File "D:\Programmes\Anaconda\envs\myapp\Scripts\hypercorn-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\__main__.py", line 287, in main
    run(config)
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\run.py", line 41, in run
    load_application(config.application_path, config.wsgi_max_body_size)
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\utils.py", line 115, in load_application
    module = import_module(import_name)
  File "D:\Programmes\Anaconda\envs\myapp\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Documents\02_APPS\05_DIFFUSION\DiffusionApp\.\main.py", line 1, in <module>
    from quart import Quart, render_template, request, session, flash, url_for, redirect, flask_patch
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\app.py", line 50, in <module>
    from .asgi import ASGIHTTPConnection, ASGILifespan, ASGIWebsocketConnection
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\asgi.py", line 29, in <module>
    from .debug import traceback_response
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\debug.py", line 8, in <module>
    from .wrappers import Response
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\wrappers\__init__.py", line 3, in <module>
    from .base import BaseRequestWebsocket
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\wrappers\base.py", line 9, in <module>
    from .. import json
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\json\__init__.py", line 7, in <module>
    from ..globals import current_app
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart\globals.py", line 16, in <module>
    app_ctx: _AppCtxGlobals = LocalProxy(  # type: ignore[assignment]
TypeError: __init__() got an unexpected keyword argument 'unbound_message'
```

It is probably related to Werkzeug.

I've tried many version:  2.0.0, 2.0.1, etc.

The version 2.2.2 has another error:
```
hypercorn main:app
---- LOCAL ACCESS ACTIVATED
Traceback (most recent call last):
  File "D:\Programmes\Anaconda\envs\myapp\Scripts\hypercorn-script.py", line 10, in <module>
    sys.exit(main())
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\__main__.py", line 287, in main
    run(config)
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\run.py", line 41, in run
    load_application(config.application_path, config.wsgi_max_body_size)
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\hypercorn\utils.py", line 115, in load_application
    module = import_module(import_name)
  File "D:\Programmes\Anaconda\envs\myapp\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "D:\Documents\02_APPS\05_DIFFUSION\DiffusionApp\.\main.py", line 16, in <module>
    from quart_csrf import CSRFProtect
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart_csrf\__init__.py", line 1, in <module>
    from .csrf import generate_csrf, validate_csrf, CSRFProtect
  File "D:\Programmes\Anaconda\envs\myapp\lib\site-packages\quart_csrf\csrf.py", line 9, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (D:\Programmes\Anaconda\envs\myapp\lib\site-packages\werkzeug\security.py)
```

How can I solve this?

Env:
- Python version: 3.9.15
- Quart version: 0.18.3

**Comment by Nicolas-M15** [comment]
I've changed to Python 3.8 and the error doesn't appear anymore.
