### ISSUE TITLE
 can't load variables with render_template

### ISSUE THREAD

**Issue by Arcader717** [pallets/quart#274]
The bug stops me from even trying to load any kind of variable

1. Setup a basic app
2. make a html page in the templates folder
3. Import `render_template` and try to load a variable into the template
4. It will error out after running and visiting the page

`from quart import Quart, render_template`
`app = Quart(__name__)`
`@app.route("/")`
`async def index():`
`  str = ""`
`  return render_template("index.html", string=str)`
`if __name__ == "__main__":`
`  app.run("0.0.0.0", 8080)`

### Error
[2023-09-20 15:28:58,478] ERROR in app: Exception on request GET /
Traceback (most recent call last):
  File "/home/runner/tests/.pythonlibs/lib/python3.10/site-packages/quart/app.py", line 1650, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/home/runner/tests/.pythonlibs/lib/python3.10/site-packages/quart/app.py", line 1676, in full_dispatch_request
    return await self.finalize_request(result, request_context)
  File "/home/runner/tests/.pythonlibs/lib/python3.10/site-packages/quart/app.py", line 1733, in finalize_request
    response = await self.make_response(result)
  File "/home/runner/tests/.pythonlibs/lib/python3.10/site-packages/quart/app.py", line 1635, in make_response
    raise TypeError(f"The response value type ({type(value).__name__}) is not valid")
TypeError: The response value type (coroutine) is not valid

I believe it should've loaded a variable into the template, not stop it from running

Environment:

- Python version: 3.10
- Quart version: 0.18.4

**Comment by davidism** [comment]
`return await render_template(...)`
