### ISSUE TITLE
cannot import name 'url_quote' from 'werkzeug.urls'

### ISSUE THREAD

**Issue by butchewing** [pallets/quart#284]
After starting the following minimal sample

```python
from quart import Quart

app = Quart(__name__)

@app.route('/')
async def hello():
    return "hello world"

app.run()
```

On `quart run` I get the following error:
```
from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls'
```

[This may be helpful](https://stackoverflow.com/questions/77213053/importerror-cannot-import-name-url-quote-from-werkzeug-urls). I did try downgrading Werkzeug, but started getting other dependency errors.

Environment: Development or Production

- Python version: 3.11.4
- Quart version: 0.19.3

A fresh install with only `pip install quart` returns the following:
```
Package      Version
------------ -------
aiofiles     23.2.1
blinker      1.6.3
click        8.1.7
Flask        3.0.0
h11          0.14.0
h2           4.1.0
hpack        4.0.0
hypercorn    0.14.4
hyperframe   6.0.1
itsdangerous 2.1.2
Jinja2       3.1.2
MarkupSafe   2.1.3
pip          23.3
priority     2.0.0
Quart        0.19.3
setuptools   65.5.0
Werkzeug     3.0.0
wsproto      1.2.0
```

**Comment by pgjones** [comment]
I think your environment must be in an odd state, as this works for me. I tried with,
```
Package      Version
------------ -------
aiofiles     23.2.1
blinker      1.6.3
click        8.1.7
Flask        3.0.0
h11          0.14.0
h2           4.1.0
hpack        4.0.0
hypercorn    0.14.4
hyperframe   6.0.1
itsdangerous 2.1.2
Jinja2       3.1.2
MarkupSafe   2.1.3
pip          23.2.1
priority     2.0.0
Quart        0.19.3
Werkzeug     3.0.0
wsproto      1.2.0
```

**Comment by butchewing** [comment]
Hmm, ok. I did a fresh install. A completely new project and still have the same issue. But, at least I know that the issue is on my end.

```
➜  quart-test python -m venv venv                
➜  quart-test source ./venv/bin/activate         
(venv) ➜  quart-test python -m pip install --upgrade pip
Requirement already satisfied: pip in ./venv/lib/python3.11/site-packages (23.1.2)
Collecting pip
  Using cached pip-23.3-py3-none-any.whl (2.1 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.1.2
    Uninstalling pip-23.1.2:
      Successfully uninstalled pip-23.1.2
Successfully installed pip-23.3
(venv) ➜  quart-test pip list
Package    Version
---------- -------
pip        23.3
setuptools 65.5.0
(venv) ➜  quart-test pip install quart
Collecting quart
  Using cached quart-0.19.3-py3-none-any.whl.metadata (5.6 kB)
Collecting aiofiles (from quart)
  Using cached aiofiles-23.2.1-py3-none-any.whl.metadata (9.7 kB)
Collecting blinker>=1.6 (from quart)
  Using cached blinker-1.6.3-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.0.0 (from quart)
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting flask>=3.0.0 (from quart)
  Using cached flask-3.0.0-py3-none-any.whl.metadata (3.6 kB)
Collecting hypercorn>=0.11.2 (from quart)
  Using cached hypercorn-0.14.4-py3-none-any.whl.metadata (5.4 kB)
Collecting itsdangerous (from quart)
  Using cached itsdangerous-2.1.2-py3-none-any.whl (15 kB)
Collecting jinja2 (from quart)
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting markupsafe (from quart)
  Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl.metadata (3.0 kB)
Collecting werkzeug>=3.0.0 (from quart)
  Using cached werkzeug-3.0.0-py3-none-any.whl.metadata (4.1 kB)
Collecting h11 (from hypercorn>=0.11.2->quart)
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting h2>=3.1.0 (from hypercorn>=0.11.2->quart)
  Using cached h2-4.1.0-py3-none-any.whl (57 kB)
Collecting priority (from hypercorn>=0.11.2->quart)
  Using cached priority-2.0.0-py3-none-any.whl (8.9 kB)
Collecting wsproto>=0.14.0 (from hypercorn>=0.11.2->quart)
  Using cached wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting hyperframe<7,>=6.0 (from h2>=3.1.0->hypercorn>=0.11.2->quart)
  Using cached hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0 (from h2>=3.1.0->hypercorn>=0.11.2->quart)
  Using cached hpack-4.0.0-py3-none-any.whl (32 kB)
Using cached quart-0.19.3-py3-none-any.whl (77 kB)
Using cached blinker-1.6.3-py3-none-any.whl (13 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached flask-3.0.0-py3-none-any.whl (99 kB)
Using cached hypercorn-0.14.4-py3-none-any.whl (58 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-macosx_10_9_universal2.whl (17 kB)
Using cached werkzeug-3.0.0-py3-none-any.whl (226 kB)
Using cached aiofiles-23.2.1-py3-none-any.whl (15 kB)
Installing collected packages: priority, markupsafe, itsdangerous, hyperframe, hpack, h11, click, blinker, aiofiles, wsproto, werkzeug, jinja2, h2, hypercorn, flask, quart
Successfully installed aiofiles-23.2.1 blinker-1.6.3 click-8.1.7 flask-3.0.0 h11-0.14.0 h2-4.1.0 hpack-4.0.0 hypercorn-0.14.4 hyperframe-6.0.1 itsdangerous-2.1.2 jinja2-3.1.2 markupsafe-2.1.3 priority-2.0.0 quart-0.19.3 werkzeug-3.0.0 wsproto-1.2.0
(venv) ➜  quart-test pip list
Package      Version
------------ -------
aiofiles     23.2.1
blinker      1.6.3
click        8.1.7
Flask        3.0.0
h11          0.14.0
h2           4.1.0
hpack        4.0.0
hypercorn    0.14.4
hyperframe   6.0.1
itsdangerous 2.1.2
Jinja2       3.1.2
MarkupSafe   2.1.3
pip          23.3
priority     2.0.0
Quart        0.19.3
setuptools   65.5.0
Werkzeug     3.0.0
wsproto      1.2.0
(venv) ➜  quart-test quart run
Traceback (most recent call last):
  File "/.pyenv/versions/3.11.4/bin/quart", line 5, in <module>
    from quart.cli import main
  File "/.pyenv/versions/3.11.4/lib/python3.11/site-packages/quart/__init__.py", line 5, in <module>
    from .app import Quart as Quart
  File "/.pyenv/versions/3.11.4/lib/python3.11/site-packages/quart/app.py", line 46, in <module>
    from werkzeug.urls import url_quote
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/.pyenv/versions/3.11.4/lib/python3.11/site-packages/werkzeug/urls.py)
(venv) ➜  quart-test 
```

**Comment by pgjones** [comment]
The Quart version must be 0.18.X or earlier given the stack trace. Have you got Quart installed globally and getting preference in the PATH for the quart run command?

**Comment by butchewing** [comment]
Thank you. Yes, I completely wiped it and started fresh again. It's working now. Thanks for following up.
