### ISSUE TITLE
asyncio error in quart/wrappers/request.py

### ISSUE THREAD

**Issue by PabloExperimental** [pallets/quart#352]
```
service     | Traceback (most recent call last):
service     |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
service     |     return await fut                                                                                                                                                                 
service     |            ^^^^^^^^^                                                                                                                                                                 
service     |   File "/usr/local/lib/python3.12/site-packages/quart/wrappers/request.py", line 89, in __await__                                                                                    
service     |     yield from self._complete.wait().__await__()                                                                                                                                     
service     |   File "/usr/local/lib/python3.12/asyncio/locks.py", line 212, in wait                                                                                                               
service     |     await fut                                                                                                                                                                        
service     | asyncio.exceptions.CancelledError                                                                                                                                                    
service     |                                                                                                                                                                                      
service     | The above exception was the direct cause of the following exception:                                                                                                                 
service     |                                                                                                                                                                                      
service     | Traceback (most recent call last):                                                                                                                                                   
service     |   File "/usr/local/lib/python3.12/site-packages/quart/wrappers/request.py", line 221, in get_data                                                                                    
service     |     raw_data = await asyncio.wait_for(self.body, timeout=self.body_timeout)                                                                                                          
service     |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                          
service     |   File "/usr/local/lib/python3.12/asyncio/tasks.py", line 519, in wait_for                                                                                                           
service     |     async with timeouts.timeout(timeout):                                                                                                                                            
service     |   File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__                                                                                                       
service     |     raise TimeoutError from exc_val                                                                                                                                                  
service     | TimeoutError                                                                                                                                                                         
service     |                                                                                                                                                                                      
service     | During handling of the above exception, another exception occurred:                                                                                                                  
service     |                                                                                                                                                                                      
service     | Traceback (most recent call last):                                                                                                                                                   
service     |   File "/home/cloudsdk/service/src/login.py", line 27, in login                                                                                                
service     |     data = await request.get_json()                                                                                                                                                  
service     |            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                  
service     |   File "/usr/local/lib/python3.12/site-packages/quart/wrappers/request.py", line 315, in get_json                                                                                    
service     |     data = await self.get_data(cache=cache, as_text=True)                                                                                                                            
service     |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                            
service     |   File "/usr/local/lib/python3.12/site-packages/quart/wrappers/request.py", line 223, in get_data                                                                                    
service     |     raise RequestTimeout()                                                                                                                                                           
service     | werkzeug.exceptions.RequestTimeout: 408 Request Timeout: The server closed the network connection because the browser didn't finish the request within the specified time. 
```
I'm deploying this in a Docker container based upon `python:3.12-slim-bookworm`. The application startup but it can't receive any request by the client.

Environment:

- Python version: 3.12.4
- Quart version: 0.19.6 (I tried also with 0.19.2 and I have the same result).
- I'm using Gunicorn with Uvicorn workers with timeout setted at 0. From [gunicorn docs](https://docs.gunicorn.org/en/stable/settings.html#timeout) this mean that timeout is disabled.

Udpate:
- Same error with `python:3.11-slim-bookworm` and `python:3.10-slim-bookworm`
- I launched gunicorn with timeout set to 120 and the problem still persists.

**Comment by aenglander** [comment]
Please provide a minimal reproducible example.

**Comment by PabloExperimental** [comment]
I will present here a minimal example.

login.py

```
from quart import Blueprint, request, session, jsonify
from quart_cors import cors, route_cors

app_route = Blueprint("login", __name__)
cors(app_route, **my settings**)

app_route.route("/api/login", methods=["POST"])
@route_cors()
async def login_route():
    try:
        data = await request.get_json() // crash here - check end of the log in first post.
    ....
```

requirement.txt
```
quart==0.19.6
quart_cors==0.7.0
Werkzeug==3.0.3
```

Dockerfile
```
FROM python:3.12-slim-bookworm

RUN apt-get update

RUN pip install --upgrade setuptools

RUN pip install --upgrade pip

RUN pip install uvicorn gunicorn

RUN pip install -r ./nanoserver/requirements.txt

```

Gunicorn is called in a docker-compose environment and launched with this configuration:
`gunicorn service.src.app:app -b 0.0.0.0:**PORT** -w 1 -k uvicorn.workers.UvicornWorker --timeout 0`

**Comment by PabloExperimental** [comment]
I will present here a minimal example.

login.py

```
from quart import Blueprint, request, session, jsonify
from quart_cors import cors, route_cors

app_route = Blueprint("login", __name__)
cors(app_route, **my settings**)

app_route.route("/api/login", methods=["POST"])
@route_cors()
async def login_route():
    try:
        data = await request.get_json() // crash here - check end of the log in first post.
    ....
```

requirement.txt
```
quart==0.19.6
quart_cors==0.7.0
Werkzeug==3.0.3
```

Dockerfile
```
FROM python:3.12-slim-bookworm

COPY . /home/cloudsdk/

RUN apt-get update

RUN pip install --upgrade setuptools

RUN pip install --upgrade pip

RUN pip install uvicorn gunicorn

RUN pip install -r ./service/requirements.txt

```

Gunicorn is called in a docker-compose environment and launched with this configuration:
`gunicorn service.src.app:app -b 0.0.0.0:**PORT** -w 1 -k uvicorn.workers.UvicornWorker --timeout 0`

**Comment by PabloExperimental** [comment]
Update:
Now the app in running normally. 

Probably some error with my Docker or the distro?
